In [15]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn import metrics

In [16]:
df = pd.read_csv('C:/emails.csv')

In [17]:
df.isnull().sum()
df.head()

Email No.  the  to  ect  and  for  of    a  you  hou  ...  connevey  jay   
0   Email 1    0   0    1    0    0   0    2    0    0  ...         0    0  \
1   Email 2    8  13   24    6    6   2  102    1   27  ...         0    0   
2   Email 3    0   0    1    0    0   0    8    0    0  ...         0    0   
3   Email 4    0   5   22    0    5   1   51    2   10  ...         0    0   
4   Email 5    7   6   17    1    5   2   57    0    9  ...         0    0   

   valued  lay  infrastructure  military  allowing  ff  dry  Prediction  
0       0    0               0         0         0   0    0           0  
1       0    0               0         0         0   1    0           0  
2       0    0               0         0         0   0    0           0  
3       0    0               0         0         0   0    0           0  
4       0    0               0         0         0   1    0           0  

[5 rows x 3002 columns]

In [18]:
# df['Prediction'] = df['Prediction'].replace({0:'Not Spam', 1:'Spam'})
df['Prediction']

0       0
1       0
2       0
3       0
4       0
       ..
5167    0
5168    0
5169    1
5170    1
5171    0
Name: Prediction, Length: 5172, dtype: int64

In [25]:
X = df.drop(columns=['Email No.', 'Prediction'], axis=1) # features
Y = df['Prediction'] # target
Y.head()

0    0
1    0
2    0
3    0
4    0
Name: Prediction, dtype: int64

In [26]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train , y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [27]:
# KNN

KN = KNeighborsClassifier(n_neighbors=7)
KN.fit(x_train, y_train)
y_predkn = KN.predict(x_test)
print(y_predkn)

[0 0 1 ... 0 1 0]


In [28]:
knnacc = metrics.accuracy_score(y_test, y_predkn)
cmknn = metrics.confusion_matrix(y_test, y_predkn)

print(knnacc)
print(cmknn)

0.8685990338164251
[[645  94]
 [ 42 254]]


In [29]:
#SVM

svmmodel = SVC(C=1)
svmmodel.fit(x_train, y_train)
y_predsvc = svmmodel.predict(x_test)
print(y_predsvc)

[0 0 1 ... 0 0 0]


In [30]:
svmacc = metrics.accuracy_score(y_test, y_predsvc)
svccm = metrics.confusion_matrix(y_test, y_predsvc)

print(svmacc)
print(svccm)

0.8173913043478261
[[727  12]
 [177 119]]
